// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgSQwZpRuT0mC9GXKuOkXNTqKCMQ6IhHI',
    appId: '1:793186198501:web:d09b766de7c9cf3dcdc50c',
    messagingSenderId: '793186198501',
    projectId: 'flutter-chat-app-1acdb',
    authDomain: 'flutter-chat-app-1acdb.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1acdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1TwuTDljGBhrPcOyg8Sm9dbDDE5azZQM',
    appId: '1:793186198501:android:5bd3574841d14f6fcdc50c',
    messagingSenderId: '793186198501',
    projectId: 'flutter-chat-app-1acdb',
    storageBucket: 'flutter-chat-app-1acdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8E9_-Y081CwQ8PKuBiG47q47BynRH-Wo',
    appId: '1:793186198501:ios:6d2b6831d44c4420cdc50c',
    messagingSenderId: '793186198501',
    projectId: 'flutter-chat-app-1acdb',
    storageBucket: 'flutter-chat-app-1acdb.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8E9_-Y081CwQ8PKuBiG47q47BynRH-Wo',
    appId: '1:793186198501:ios:9f9a3b4a0fddfe16cdc50c',
    messagingSenderId: '793186198501',
    projectId: 'flutter-chat-app-1acdb',
    storageBucket: 'flutter-chat-app-1acdb.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
